from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from mechcad.feature_plan import FeaturePlan, dimension_evidence, dimension_value, validate_feature_plan
from mechcad.sandbox.build123d_runner import SandboxResult, run_build123d


@dataclass(frozen=True)
class FeatureExecutionResult:
    ok: bool
    code: str
    sandbox: SandboxResult
    modeled_features: list[str] = field(default_factory=list)
    skipped_features: list[dict[str, str]] = field(default_factory=list)
    validation_errors: list[str] = field(default_factory=list)


def execute_feature_plan(raw_plan: dict, run_dir: Path, timeout: int) -> FeatureExecutionResult:
    plan, errors = validate_feature_plan(raw_plan)
    if plan is None:
        code = _failure_code(errors)
        return FeatureExecutionResult(
            ok=False,
            code=code,
            sandbox=SandboxResult(False, "", "FeaturePlan validation failed: " + "; ".join(errors), None, None),
            validation_errors=errors,
        )

    code, modeled, skipped = build_feature_plan_code(plan)
    sandbox = run_build123d(code, run_dir=run_dir, timeout=timeout)
    return FeatureExecutionResult(
        ok=sandbox.ok,
        code=code,
        sandbox=sandbox,
        modeled_features=modeled,
        skipped_features=skipped,
        validation_errors=[],
    )


def build_feature_plan_code(plan: FeaturePlan | dict) -> tuple[str, list[str], list[dict[str, str]]]:
    if isinstance(plan, dict):
        validated, errors = validate_feature_plan(plan)
        if validated is None:
            return _failure_code(errors), [], [{"feature": "FeaturePlan", "reason": "; ".join(errors)}]
        plan = validated

    modeled: list[str] = []
    skipped: list[dict[str, str]] = []
    lines = [
        "from build123d import *",
        "",
        "# Generated by MechCAD FeaturePlan executor. AI JSON is validated before this code is emitted.",
        "with BuildPart() as part:",
    ]
    if plan.base_feature is None:
        lines.append('    raise RuntimeError("FeaturePlan has no supported base_feature.")')
        return "\n".join(lines + _export_lines()), modeled, skipped

    body_kind = plan.base_feature.type
    body_dims = plan.base_feature.dimensions
    bore_to_cut: tuple[float, float] | None = None
    context: dict[str, float] = {}

    if body_kind in {"hollow_cylinder", "cylinder_base", "revolved_axial_profile"}:
        outer = dimension_value(body_dims, "outer_diameter", "diameter")
        length = dimension_value(body_dims, "length", "overall_length", "height")
        inner = dimension_value(body_dims, "inner_diameter", "bore_diameter", "inside_diameter")
        if outer is None or length is None or outer <= 0 or length <= 0:
            lines.append('    raise RuntimeError("Cylinder base is missing outer_diameter/length.")')
            skipped.append({"feature": "base_feature", "reason": "Missing cylinder outer_diameter or length."})
            return "\n".join(lines + _export_lines()), modeled, skipped
        context.update({"outer_diameter": outer, "length": length})
        lines.append(f"    # base_feature: {body_kind}, OD {outer:g} mm, length {length:g} mm.")
        lines.append(
            f"    Cylinder(radius={outer / 2:g}, height={length:g}, align=(Align.CENTER, Align.CENTER, Align.MIN))"
        )
        modeled.append(plan.base_feature.id)
        if body_kind == "hollow_cylinder":
            if inner is None or inner <= 0 or inner >= outer:
                skipped.append({"feature": "base_bore", "reason": "Missing or invalid inner_diameter."})
            else:
                bore_to_cut = (inner, length)
                context["inner_diameter"] = inner
    elif body_kind == "box_base":
        length = dimension_value(body_dims, "length", "x", "width")
        width = dimension_value(body_dims, "width", "y", "depth")
        height = dimension_value(body_dims, "height", "z", "thickness")
        if length is None or width is None or height is None or min(length, width, height) <= 0:
            lines.append('    raise RuntimeError("Box base is missing length/width/height.")')
            skipped.append({"feature": "base_feature", "reason": "Missing box length, width or height."})
            return "\n".join(lines + _export_lines()), modeled, skipped
        context.update({"length": length, "width": width, "height": height})
        lines.append(f"    # base_feature: box_base, {length:g} x {width:g} x {height:g} mm.")
        lines.append(
            f"    Box({length:g}, {width:g}, {height:g}, align=(Align.CENTER, Align.CENTER, Align.MIN))"
        )
        modeled.append(plan.base_feature.id)
    else:
        lines.append(f'    raise RuntimeError("Unsupported base_feature type: {body_kind}")')
        skipped.append({"feature": "base_feature", "reason": f"Unsupported base_feature type: {body_kind}"})
        return "\n".join(lines + _export_lines()), modeled, skipped

    for feature in plan.features:
        added = _feature_lines(feature, context)
        if added is None:
            skipped.append({"feature": feature.id, "reason": _skip_reason(feature)})
            lines.append(f"    # UNRESOLVED: {feature.id} skipped by executor: {_skip_reason(feature)}")
            continue
        lines.extend(added)
        modeled.append(feature.id)

    if bore_to_cut is not None:
        inner, length = bore_to_cut
        lines.append(f"    # base bore from inner diameter {inner:g} mm.")
        lines.append(
            f"    Cylinder(radius={inner / 2:g}, height={length + 2:g}, align=(Align.CENTER, Align.CENTER, Align.MIN), mode=Mode.SUBTRACT)"
        )

    lines.extend(_export_lines())
    return "\n".join(lines), modeled, skipped


def _feature_lines(feature, context: dict[str, float]) -> list[str] | None:
    dims = feature.dimensions
    kind = feature.type
    x = feature.placement.x or 0.0
    y = feature.placement.y or 0.0
    z = feature.placement.z or 0.0
    axis = feature.placement.axis

    if kind == "annular_groove":
        outer = context.get("outer_diameter")
        z_start = dimension_value(dims, "z_start", "axial_start_from_bottom")
        width = dimension_value(dims, "axial_width", "width", "axial_length")
        reduced = dimension_value(dims, "reduced_outer_diameter", "outer_diameter", "diameter")
        length = context.get("length")
        inner = context.get("inner_diameter", 0.0)
        if outer is None or length is None or z_start is None or width is None or reduced is None:
            return None
        if width <= 0 or reduced <= inner or reduced >= outer or z_start < 0 or z_start + width > length:
            return None
        evidence = dimension_evidence(dims, "axial_width", "reduced_outer_diameter")
        return [
            f"    # {feature.id}: annular groove. {evidence}",
            f"    with Locations((0, 0, {z_start:g})):",
            f"        Cylinder(radius={outer / 2:g}, height={width:g}, align=(Align.CENTER, Align.CENTER, Align.MIN), mode=Mode.SUBTRACT)",
            f"        Cylinder(radius={reduced / 2:g}, height={width:g}, align=(Align.CENTER, Align.CENTER, Align.MIN), mode=Mode.ADD)",
        ]

    if kind in {"through_hole", "blind_hole", "counterbore_hole"}:
        diameter = dimension_value(dims, "diameter", "hole_diameter")
        depth = dimension_value(dims, "depth")
        if diameter is None or diameter <= 0:
            return None
        if kind == "through_hole":
            depth = _through_depth(axis, context)
            z = _through_start(axis, context)
        elif depth is None or depth <= 0:
            return None
        return [
            f"    # {feature.id}: {kind} diameter {diameter:g} mm.",
            f"    with Locations(({x:g}, {y:g}, {z:g})):",
            f"        Cylinder(radius={diameter / 2:g}, height={depth:g}, rotation={_rotation(axis)}, align=(Align.CENTER, Align.CENTER, Align.MIN), mode=Mode.SUBTRACT)",
        ]

    if kind in {"boss_cylinder"}:
        diameter = dimension_value(dims, "diameter", "outer_diameter")
        height = dimension_value(dims, "height", "length")
        if diameter is None or height is None or diameter <= 0 or height <= 0:
            return None
        return [
            f"    # {feature.id}: boss cylinder.",
            f"    with Locations(({x:g}, {y:g}, {z:g})):",
            f"        Cylinder(radius={diameter / 2:g}, height={height:g}, rotation={_rotation(axis)}, align=(Align.CENTER, Align.CENTER, Align.MIN), mode=Mode.ADD)",
        ]

    if kind in {"rectangular_pad", "rib_box", "rectangular_slot", "rectangular_pocket"}:
        lx = dimension_value(dims, "length", "x")
        wy = dimension_value(dims, "width", "y")
        hz = dimension_value(dims, "height", "depth", "z")
        if lx is None or wy is None or hz is None or min(lx, wy, hz) <= 0:
            return None
        mode = "Mode.SUBTRACT" if feature.operation == "remove" or kind in {"rectangular_slot", "rectangular_pocket"} else "Mode.ADD"
        return [
            f"    # {feature.id}: {kind}.",
            f"    with Locations(({x:g}, {y:g}, {z:g})):",
            f"        Box({lx:g}, {wy:g}, {hz:g}, align=(Align.CENTER, Align.CENTER, Align.MIN), mode={mode})",
        ]

    if kind == "circular_pattern":
        count = dimension_value(dims, "count")
        pitch_radius = dimension_value(dims, "pitch_radius", "bolt_circle_radius", "radius")
        diameter = dimension_value(dims, "diameter", "hole_diameter")
        depth = dimension_value(dims, "depth") or _through_depth(axis, context)
        if count is None or pitch_radius is None or diameter is None:
            return None
        if count < 2 or pitch_radius <= 0 or diameter <= 0 or depth <= 0 or axis != "Z":
            return None
        return [
            f"    # {feature.id}: circular hole pattern, {int(count)} holes.",
            f"    with Locations(({x:g}, {y:g}, {z:g})):",
            f"        with PolarLocations(radius={pitch_radius:g}, count={int(count)}):",
            f"            Cylinder(radius={diameter / 2:g}, height={depth:g}, align=(Align.CENTER, Align.CENTER, Align.MIN), mode=Mode.SUBTRACT)",
        ]

    if kind == "linear_pattern":
        count = dimension_value(dims, "count")
        spacing = dimension_value(dims, "spacing", "pitch")
        diameter = dimension_value(dims, "diameter", "hole_diameter")
        depth = dimension_value(dims, "depth") or _through_depth(axis, context)
        if count is None or spacing is None or diameter is None:
            return None
        if count < 2 or spacing <= 0 or diameter <= 0 or depth <= 0 or axis != "Z":
            return None
        start = -spacing * (int(count) - 1) / 2.0
        points = ", ".join(f"({x + start + spacing * i:g}, {y:g}, {z:g})" for i in range(int(count)))
        return [
            f"    # {feature.id}: linear hole pattern, {int(count)} holes.",
            f"    with Locations({points}):",
            f"        Cylinder(radius={diameter / 2:g}, height={depth:g}, align=(Align.CENTER, Align.CENTER, Align.MIN), mode=Mode.SUBTRACT)",
        ]

    return None


def _through_depth(axis: str, context: dict[str, float]) -> float:
    if axis == "X":
        return context.get("length", 10.0) + 2.0
    if axis == "Y":
        return context.get("width", context.get("outer_diameter", 10.0)) + 2.0
    return context.get("height", context.get("length", 10.0)) + 2.0


def _through_start(axis: str, context: dict[str, float]) -> float:
    if axis == "Z":
        return -1.0
    if axis == "X":
        return -(context.get("length", 10.0) / 2.0) - 1.0
    return -(context.get("width", 10.0) / 2.0) - 1.0


def _rotation(axis: str) -> tuple[int, int, int]:
    if axis == "X":
        return (0, 90, 0)
    if axis == "Y":
        return (90, 0, 0)
    return (0, 0, 0)


def _skip_reason(feature) -> str:
    if feature.unresolved:
        return "; ".join(map(str, feature.unresolved))
    return "missing required dimensions, placement, or supported construction."


def _export_lines() -> list[str]:
    return [
        "",
        'export_step(part.part, "model.step")',
        'export_stl(part.part, "model.stl")',
        "",
    ]


def _failure_code(errors: list[str]) -> str:
    message = "; ".join(errors).replace('"', "'")
    return (
        "from build123d import *\n\n"
        f'raise RuntimeError("FeaturePlan validation failed: {message}")\n'
    )
