from __future__ import annotations

import base64
import json
import shutil
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from PIL import Image

from mechcad.api_config import ApiConfig
from mechcad.clients.minimax import generate_feature_plan
from mechcad.clients.qwen import analyze_sketch
from mechcad.clarification import build_clarification_questions, clarification_markdown, dimension_ledger_markdown
from mechcad.feature_executor import execute_feature_plan
from mechcad.preprocess import preprocess_image
from mechcad.planner import build_model_plan
from mechcad.sandbox.build123d_runner import SandboxResult
from mechcad.sandbox.mesh_tools import stl_to_obj
from mechcad.sandbox.ocp_fallback import generate_ocp_fallback


RUNS_DIR = Path("outputs") / "runs"


@dataclass(frozen=True)
class GenerationSettings:
    part_family: str = "自动判断"
    quality_mode: str = "更稳妥"
    force_real_api: bool = False
    api_config: ApiConfig = field(default_factory=ApiConfig)
    qwen_model: str | None = None
    minimax_model: str | None = None
    temperature: float = 0.25
    sandbox_timeout: int = 30
    clarification_mode: str = "interactive"
    clarification_answers: str = ""
    operation_mode: str = "smart"


@dataclass(frozen=True)
class GenerationResult:
    run_id: str
    qwen_json: dict[str, Any]
    model_plan: dict[str, Any]
    build123d_code: str
    sandbox: SandboxResult
    report_markdown: str
    obj_path: str | None
    step_path: str | None
    stl_path: str | None
    clarification_questions: list[str]


def run_generation(image: Image.Image, description: str, settings: GenerationSettings) -> GenerationResult:
    run_id = uuid.uuid4().hex[:10]
    run_dir = RUNS_DIR / run_id
    run_dir.mkdir(parents=True, exist_ok=True)

    original_path = run_dir / "input.png"
    image.convert("RGB").save(original_path)

    processed_path, image_metrics = preprocess_image(original_path, run_dir)
    image_b64 = _encode_file(original_path)
    processed_b64 = _encode_file(processed_path)

    mode_instruction = (
        "\n\n建模模式：严格模式。只允许使用图纸或用户明确确认的数值、位置和关系。"
        "任何缺失、模糊或冲突信息必须列入 unresolved 并向用户提问；不得用比例估计、常见规格、"
        "对称假设或默认值补齐。未经确认的建议不得写入可执行 FeaturePlan。"
        if settings.operation_mode == "strict"
        else "\n\n建模模式：智能模式。你可以像工程师一样主动检查功能、制造意图、基准、可装配性和尺寸关系，"
        "发现歧义时提出具体问题，也可以给出带理由的设计建议；但建议必须单独标为 suggestion/unresolved，"
        "未经用户确认不得写入可执行尺寸。不得把猜测伪装成图纸事实。"
    )
    effective_description = description + mode_instruction
    if settings.clarification_answers.strip():
        effective_description += (
            "\n\n用户对上一轮建模疑问的确认如下。将这些回答视为本轮建模约束，"
            "只在不与图中明确尺寸冲突时采用：\n" + settings.clarification_answers.strip()
        )

    qwen_json = analyze_sketch(
        image_path=processed_path,
        image_base64=processed_b64,
        description=effective_description,
        settings=settings,
        image_metrics=image_metrics,
    )
    (run_dir / "qwen_analysis.json").write_text(json.dumps(qwen_json, ensure_ascii=False, indent=2), encoding="utf-8")
    seed_model_plan = build_model_plan(qwen_json, effective_description, settings.part_family)
    (run_dir / "seed_model_plan.json").write_text(json.dumps(seed_model_plan, ensure_ascii=False, indent=2), encoding="utf-8")
    model_plan = generate_feature_plan(
        image_base64=image_b64,
        description=effective_description,
        qwen_json=qwen_json,
        model_plan=seed_model_plan,
        settings=settings,
    )
    (run_dir / "model_plan.json").write_text(json.dumps(model_plan, ensure_ascii=False, indent=2), encoding="utf-8")

    execution = execute_feature_plan(model_plan, run_dir=run_dir, timeout=settings.sandbox_timeout)
    build123d_code = execution.code
    sandbox = execution.sandbox
    if sandbox.ok:
        sandbox = SandboxResult(
            ok=True,
            stdout=(
                "Generated by FeaturePlan executor.\n"
                f"Modeled features: {', '.join(execution.modeled_features) or 'none'}\n"
                f"Skipped features: {json.dumps(execution.skipped_features, ensure_ascii=False)}\n"
                + sandbox.stdout
            ),
            stderr=sandbox.stderr,
            step_path=sandbox.step_path,
            stl_path=sandbox.stl_path,
        )
    if not sandbox.ok and settings.operation_mode != "strict":
        step_path, stl_path, fallback_message = generate_ocp_fallback(run_dir, qwen_json)
        sandbox = SandboxResult(
            ok=bool(step_path and stl_path),
            stdout=fallback_message,
            stderr=(
                "FeaturePlan executor failed before OCP fallback.\n"
                + sandbox.stderr
                + "\nSkipped features: "
                + json.dumps(execution.skipped_features, ensure_ascii=False)
            ),
            step_path=step_path,
            stl_path=stl_path,
        )
    elif not sandbox.ok:
        sandbox = SandboxResult(
            ok=False,
            stdout="Strict mode: Build123d failed; no geometric fallback was generated.",
            stderr=sandbox.stderr,
            step_path=None,
            stl_path=None,
        )

    if not sandbox.ok and settings.operation_mode == "strict":
        step_path = None
        stl_path = None
        obj_path = None
    else:
        step_path = _copy_or_placeholder(sandbox.step_path, run_dir / "model.step", "STEP generation failed.")
        stl_path = _copy_or_placeholder(sandbox.stl_path, run_dir / "model.stl", "STL generation failed.")
        preview_source = _stl_to_obj_path(stl_path, run_dir) or Path(stl_path)
        obj_path = _copy_or_placeholder(preview_source, run_dir / "model.obj", "OBJ generation failed.")
    clarification_questions = []
    if settings.clarification_mode == "interactive" or settings.operation_mode == "smart":
        clarification_questions = build_clarification_questions(qwen_json, model_plan)
    report = _format_report_v2(run_id, qwen_json, model_plan, sandbox, settings, clarification_questions)
    (run_dir / "report.md").write_text(report, encoding="utf-8")
    (run_dir / "sandbox_result.json").write_text(
        json.dumps(
            {
                "ok": sandbox.ok,
                "stdout": sandbox.stdout,
                "stderr": sandbox.stderr,
                "step_path": sandbox.step_path,
                "stl_path": sandbox.stl_path,
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    return GenerationResult(
        run_id=run_id,
        qwen_json=qwen_json,
        model_plan=model_plan,
        build123d_code=build123d_code,
        sandbox=sandbox,
        report_markdown=report,
        obj_path=str(obj_path) if obj_path else None,
        step_path=str(step_path) if step_path else None,
        stl_path=str(stl_path) if stl_path else None,
        clarification_questions=clarification_questions,
    )


def _encode_file(path: Path) -> str:
    return base64.b64encode(path.read_bytes()).decode("ascii")


def _copy_or_placeholder(source: str | None, target: Path, message: str) -> Path:
    if source and Path(source).exists():
        src = Path(source)
        if src.resolve() != target.resolve():
            shutil.copyfile(src, target)
        return target
    target.write_text(message, encoding="utf-8")
    return target


def _stl_to_obj_path(stl_path: Path, run_dir: Path) -> Path | None:
    src = Path(stl_path)
    if not src.exists() or src.stat().st_size < 84:
        return None
    obj_path = run_dir / "model.obj"
    try:
        return stl_to_obj(src, obj_path)
    except Exception:
        return None


def _format_report_v2(
    run_id: str,
    qwen_json: dict[str, Any],
    model_plan: dict[str, Any],
    sandbox: SandboxResult,
    settings: GenerationSettings,
    clarification_questions: list[str] | None = None,
) -> str:
    mode = "真实 API" if qwen_json.get("source") == "api" else "本地演示/降级"
    status = "成功生成 STEP/STL" if sandbox.ok else "生成失败，已返回错误信息"
    if sandbox.stdout.startswith("Generated by FeaturePlan executor"):
        execution_path = "FeaturePlan 受控 Build123d executor"
    elif sandbox.stdout.startswith("Generated by direct OCP fallback"):
        execution_path = "FeaturePlan/Build123d 未通过，已用 OCP 兜底导出"
    else:
        execution_path = "Build123d 执行失败"

    domain = qwen_json.get("domain", {})
    if not isinstance(domain, dict):
        domain = {"part_family": str(domain)}
    uncertainties = qwen_json.get("uncertainties", [])
    checks = qwen_json.get("consistency_checks", {})
    unresolved = model_plan.get("unresolved", [])
    unresolved_text = "；".join(item.get("reason", str(item)) for item in unresolved) if unresolved else "无"
    uncertainty_text = "；".join(map(str, uncertainties)) if uncertainties else "暂无"
    feature_count = len(model_plan.get("features", [])) if isinstance(model_plan.get("features"), list) else 0
    plan_source = model_plan.get("source", "unknown")

    questions_text = clarification_markdown(clarification_questions or [])
    dimensions_text = dimension_ledger_markdown(qwen_json)
    return (
        "### 运行结果\n"
        f"- Run ID: `{run_id}`\n"
        f"- 模式: `{mode}`\n"
        f"- 策略: `{settings.quality_mode}`\n"
        f"- 建模模式: `{settings.operation_mode}`\n"
        f"- 状态: **{status}**\n"
        f"- CAD 执行路径: `{execution_path}`\n"
        f"- 识别类型: `{domain.get('part_family', '未知')}`\n"
        f"- FeaturePlan: `{model_plan.get('part_family', '未知')}` / `{plan_source}` / `{feature_count}` features\n"
        f"- 计划未解决项: {unresolved_text}\n"
        f"- 主要不确定项: {uncertainty_text}\n"
        f"- 一致性检查: `{checks}`\n"
        + (f"\n{dimensions_text}\n" if dimensions_text else "")
        + (f"\n{questions_text}\n" if questions_text else "")
    )


def _format_report(
    run_id: str,
    qwen_json: dict[str, Any],
    model_plan: dict[str, Any],
    sandbox: SandboxResult,
    settings: GenerationSettings,
) -> str:
    mode = "真实 API" if qwen_json.get("source") == "api" else "本地演示/降级"
    checks = qwen_json.get("consistency_checks", {})
    uncertainties = qwen_json.get("uncertainties", [])
    uncertainty_text = "；".join(map(str, uncertainties)) if uncertainties else "暂无"
    status = "成功生成 STEP/STL" if sandbox.ok else "生成失败，已返回错误信息"
    fallback_note = ""
    if sandbox.stdout.startswith("Generated by direct OCP fallback"):
        fallback_note = "\n- CAD 执行路径: `Build123d 未通过，已用 OCP 兜底导出`"
    domain = qwen_json.get("domain", {})
    if not isinstance(domain, dict):
        domain = {"part_family": str(domain)}
    plan_status = model_plan.get("status", "unknown")
    unresolved_plan = model_plan.get("unresolved", [])
    unresolved_text = "；".join(item.get("reason", str(item)) for item in unresolved_plan) if unresolved_plan else "无"
    return (
        f"### 运行结果\n"
        f"- Run ID: `{run_id}`\n"
        f"- 模式: `{mode}`\n"
        f"- 策略: `{settings.quality_mode}`\n"
        f"- 状态: **{status}**\n"
        f"{fallback_note}\n"
        f"- 识别类型: `{domain.get('part_family', '未知')}`\n"
        f"- 建模计划: `{model_plan.get('part_family', '未知')}` / `{plan_status}`\n"
        f"- 计划未解决项: {unresolved_text}\n"
        f"- 主要不确定项: {uncertainty_text}\n"
        f"- 一致性检查: `{checks}`\n"
    )


def _fallback_build123d_code(description: str, part_family: str) -> str:
    return f'''
from build123d import *

# Fallback model generated after the model code failed sandbox execution.
with BuildPart() as part:
    Box(70, 42, 8)
    with Locations((22, 0, 4), (-22, 0, 4)):
        Hole(4)
    fillet(part.edges().filter_by(Axis.Z), radius=2)

export_step(part.part, "model.step")
export_stl(part.part, "model.stl")
'''
