from __future__ import annotations

"""Planner model integration: turn vision JSON + description into FeaturePlanV3."""

import json
from typing import Any

from backend.mechcad_ai.client import ApiCallError, chat_completion, has_configured_model, parse_json_object
from backend.mechcad_ai.normalize import normalize_ai_plan, normalize_feature_edit_set
from backend.mechcad_ai.prompts import get_prompt
from backend.schemas import ClarificationQuestion, FeatureEditSet, FeaturePlanV3


def generate_feature_plan(
    description: str,
    vision_json: dict[str, Any] | None,
    settings,
    mode: str = "strict",
    smart_fill_policy: str = "limited_fill",
    language: str = "zh",
) -> FeaturePlanV3 | None:
    """Ask the planner model for a FeaturePlanV3 JSON.

    Returns None when the model is not configured, fails, or returns an invalid
    plan, so the caller can fall back to the deterministic local planner.
    """
    if not has_configured_model(settings, "planner"):
        return None

    prompt = get_prompt("feature_planning", language)
    seed = _stub_seed_from_description(description, language)
    if language == "en":
        context = {
            "user_function_description": description,
            "vision_drawing_json": vision_json or {},
            "conservative_seed_plan_for_reference_only": seed,
            "mode": mode,
            "smart_fill_policy": smart_fill_policy,
        }
        instruction = "\n\nOutput FeaturePlanV3 JSON (schema_version=3.0). Do not output Markdown or explanatory prose."
    else:
        context = {
            "用户功能描述": description,
            "视觉读图 JSON": vision_json or {},
            "保守种子计划，仅作参考，可扩展": seed,
            "模式": mode,
            "智能补全策略": smart_fill_policy,
        }
        instruction = "\n\n请输出 FeaturePlanV3 JSON（schema_version=3.0）。不要输出 Markdown 或解释性散文。"
    messages = [
        {"role": "system", "content": prompt},
        {
            "role": "user",
            "content": json.dumps(context, ensure_ascii=False, indent=2)
            + instruction,
        },
    ]
    try:
        content = chat_completion(
            settings,
            "planner",
            messages,
            max_tokens=4096,
            temperature=0.1,
            response_json=True,
        )
    except ApiCallError:
        raise

    try:
        parsed = parse_json_object(content)
        plan = FeaturePlanV3.model_validate(normalize_ai_plan(parsed, language))
    except Exception:
        return None
    if plan.base_feature is None:
        return None
    plan.assumptions.append(
        "FeaturePlan was generated by the planner model and has not been item-by-item confirmed by the user."
        if language == "en"
        else "FeaturePlan 由 planner 模型生成，尚未经过用户逐项确认。"
    )
    return plan


def chat_edit_operations(
    plan: FeaturePlanV3,
    message: str,
    settings,
    language: str = "zh",
) -> FeatureEditSet | None:
    """Ask the planner model for feature-level edit operations.

    The model must return a FeatureEditSet, never a full FeaturePlanV3. The
    backend applies and validates the operations itself.
    """
    if not has_configured_model(settings, "planner"):
        return None

    prompt = get_prompt("chat_edit", language)
    if language == "en":
        context = {
            "current_FeaturePlanV3": plan.model_dump(),
            "user_natural_language_edit": message,
            "mode": getattr(settings, "operation_mode", "strict"),
            "smart_fill_policy": getattr(settings, "smart_fill_policy", "limited_fill"),
        }
        instruction = "\n\nOutput FeatureEditSet JSON: operations (add/update/delete/change_type) and optional questions. Do not output a full FeaturePlanV3, Markdown, or explanatory prose."
    else:
        context = {
            "当前 FeaturePlanV3": plan.model_dump(),
            "用户自然语言修改": message,
            "模式": getattr(settings, "operation_mode", "strict"),
            "智能补全策略": getattr(settings, "smart_fill_policy", "limited_fill"),
        }
        instruction = "\n\n请输出 FeatureEditSet JSON：operations（add/update/delete/change_type）和可选 questions。不要输出完整 FeaturePlanV3、Markdown 或解释性散文。"
    messages = [
        {"role": "system", "content": prompt},
        {
            "role": "user",
            "content": json.dumps(context, ensure_ascii=False, indent=2)
            + instruction,
        },
    ]
    try:
        content = chat_completion(
            settings,
            "planner",
            messages,
            max_tokens=4096,
            temperature=0.1,
            response_json=True,
        )
    except ApiCallError:
        return None

    try:
        parsed = parse_json_object(content)
        edit_set = FeatureEditSet.model_validate(normalize_feature_edit_set(parsed, language))
    except Exception:
        return None
    if not edit_set.operations and not edit_set.questions:
        return None
    return edit_set


def _stub_seed_from_description(description: str, language: str = "zh") -> dict[str, Any]:
    """A minimal, honest seed that never invents executable dimensions."""
    return {
        "schema_version": "3.0",
        "units": "mm",
        "part_family": "unknown",
        "base_feature": None,
        "features": [],
        "unresolved": [{"feature": "base_body", "reason": "等待视觉读图或用户确认尺寸" if language == "zh" else "waiting for vision reading or user-confirmed dimensions"}],
        "description": description,
    }


def questions_from_plan(plan: FeaturePlanV3) -> list[ClarificationQuestion]:
    """Convert unresolved plan items into user-facing clarification questions."""
    from backend.ai import questions_from_plan as _local_questions

    return _local_questions(plan)
