from __future__ import annotations

from pathlib import Path
from typing import Any


def generate_ocp_fallback(run_dir: Path, qwen_json: dict[str, Any]) -> tuple[str | None, str | None, str]:
    """Generate a simple CAD body directly with OCP when Build123d is unavailable."""
    try:
        from OCP.BRepPrimAPI import BRepPrimAPI_MakeBox, BRepPrimAPI_MakeCylinder
        from OCP.BRepAlgoAPI import BRepAlgoAPI_Cut, BRepAlgoAPI_Fuse
        from OCP.BRepMesh import BRepMesh_IncrementalMesh
        from OCP.gp import gp_Ax2, gp_Dir, gp_Pnt
        from OCP.IFSelect import IFSelect_RetDone
        from OCP.STEPControl import STEPControl_AsIs, STEPControl_Writer
        from OCP.StlAPI import StlAPI_Writer
    except Exception as exc:
        return None, None, f"OCP fallback import failed: {exc}"

    domain = qwen_json.get("domain", {})
    family = domain.get("part_family", "连接板") if isinstance(domain, dict) else str(domain or "连接板")
    sketch = qwen_json.get("sketch", {})
    try:
        if _looks_like_tube(family, sketch):
            dims = _tube_dimensions(sketch)
            axis = gp_Ax2(gp_Pnt(0, 0, 0), gp_Dir(0, 0, 1))
            shape = BRepPrimAPI_MakeCylinder(axis, dims["outer_radius"], dims["length"]).Shape()
            bore_axis = gp_Ax2(gp_Pnt(0, 0, -2), gp_Dir(0, 0, 1))
            hole = BRepPrimAPI_MakeCylinder(bore_axis, dims["inner_radius"], dims["length"] + 4).Shape()
            shape = BRepAlgoAPI_Cut(shape, hole).Shape()
            for groove in dims["grooves"]:
                ring = _make_annular_cut(
                    groove["radius"],
                    dims["outer_radius"],
                    groove["z_start"],
                    groove["width"],
                    gp_Ax2,
                    gp_Dir,
                    gp_Pnt,
                    BRepPrimAPI_MakeCylinder,
                    BRepAlgoAPI_Cut,
                )
                shape = BRepAlgoAPI_Cut(shape, ring).Shape()
        elif family == "法兰":
            shape = BRepPrimAPI_MakeCylinder(32, 8).Shape()
            center_hole = BRepPrimAPI_MakeCylinder(10, 12).Shape()
            shape = BRepAlgoAPI_Cut(shape, center_hole).Shape()
        elif family == "轴套":
            shape = BRepPrimAPI_MakeCylinder(18, 36).Shape()
            hole = BRepPrimAPI_MakeCylinder(8, 42).Shape()
            shape = BRepAlgoAPI_Cut(shape, hole).Shape()
        elif family == "支架":
            vertical = BRepPrimAPI_MakeBox(70, 12, 48).Shape()
            base = BRepPrimAPI_MakeBox(70, 48, 10).Shape()
            shape = BRepAlgoAPI_Fuse(vertical, base).Shape()
        else:
            shape = BRepPrimAPI_MakeBox(80, 45, 8).Shape()
            for x in (22, 58):
                axis = gp_Ax2(gp_Pnt(x, 22.5, -2), gp_Dir(0, 0, 1))
                hole = BRepPrimAPI_MakeCylinder(axis, 5, 12).Shape()
                shape = BRepAlgoAPI_Cut(shape, hole).Shape()

        step_path = run_dir / "model.step"
        stl_path = run_dir / "model.stl"

        step_writer = STEPControl_Writer()
        step_writer.Transfer(shape, STEPControl_AsIs)
        if step_writer.Write(str(step_path)) != IFSelect_RetDone:
            raise RuntimeError("STEP writer failed")

        BRepMesh_IncrementalMesh(shape, 0.5)
        stl_writer = StlAPI_Writer()
        stl_writer.Write(shape, str(stl_path))
        return str(step_path), str(stl_path), "Generated by direct OCP fallback."
    except Exception as exc:
        return None, None, f"OCP fallback generation failed: {exc}"


def _looks_like_tube(family: str, sketch: Any) -> bool:
    text = f"{family} {sketch}".lower()
    tokens = ["tube", "bushing", "sleeve", "圆管", "轴套", "薄壁", "cylindrical", "inner_diameter", "outer_diameter"]
    return any(token in text for token in tokens)


def _tube_dimensions(sketch: Any) -> dict[str, float]:
    outer = _find_dimension(sketch, ("outer_diameter", "outside_diameter", "od", "diameter"), 50.0, prefer="max")
    inner = _find_dimension(sketch, ("inner_diameter", "inside_diameter", "bore_diameter", "id"), 40.0, prefer="min")
    length = _find_dimension(sketch, ("overall_length", "total_height", "total_length", "length", "height"), 300.0, prefer="max")
    if inner >= outer:
        inner = outer * 0.75
    grooves = _tube_grooves(sketch, outer / 2.0, inner / 2.0, length)
    return {
        "outer_radius": max(outer / 2.0, 1.0),
        "inner_radius": max(inner / 2.0, 0.5),
        "length": max(length, 1.0),
        "grooves": grooves,
    }


def _make_annular_cut(
    inner_radius: float,
    outer_radius: float,
    z_start: float,
    width: float,
    gp_Ax2,
    gp_Dir,
    gp_Pnt,
    BRepPrimAPI_MakeCylinder,
    BRepAlgoAPI_Cut,
):
    eps = 0.2
    outer_axis = gp_Ax2(gp_Pnt(0, 0, z_start), gp_Dir(0, 0, 1))
    inner_axis = gp_Ax2(gp_Pnt(0, 0, z_start - eps), gp_Dir(0, 0, 1))
    outer_cut = BRepPrimAPI_MakeCylinder(outer_axis, outer_radius + eps, width).Shape()
    inner_keep = BRepPrimAPI_MakeCylinder(inner_axis, inner_radius, width + 2 * eps).Shape()
    return BRepAlgoAPI_Cut(outer_cut, inner_keep).Shape()


def _tube_grooves(sketch: Any, outer_radius: float, inner_radius: float, length: float) -> list[dict[str, float]]:
    text = str(sketch).lower()
    if not any(token in text for token in ("groove", "slot", "槽", "环槽", "ring")):
        return []

    width = _find_dimension(sketch, ("groove_width", "slot_depth", "slot_height", "groove_depth"), 10.0, prefer="max")
    if width <= 0 or width > length / 4:
        width = 10.0

    diameters = _collect_keyed_numbers(sketch, ("top_slot_width", "bottom_slot_width", "slot_width", "groove_diameter", "step_diameter"))
    groove_radii = [
        value / 2.0
        for value in diameters
        if inner_radius + 0.2 < value / 2.0 < outer_radius - 0.2
    ]
    if not groove_radii:
        groove_radii = [max(inner_radius + 0.8, outer_radius - 2.0)]

    grooves: list[dict[str, float]] = []
    bottom_radius = groove_radii[-1]
    top_radius = groove_radii[0]
    grooves.append({"radius": bottom_radius, "z_start": 0.0, "width": width})
    grooves.append({"radius": top_radius, "z_start": max(length - width, 0.0), "width": width})
    return grooves


def _find_dimension(value: Any, keys: tuple[str, ...], default: float, prefer: str = "first") -> float:
    numbers = _collect_keyed_numbers(value, keys)
    if not numbers:
        return default
    if prefer == "max":
        return max(numbers)
    if prefer == "min":
        return min(numbers)
    return numbers[0]


def _collect_keyed_numbers(value: Any, keys: tuple[str, ...]) -> list[float]:
    found: list[float] = []
    if isinstance(value, dict):
        for k, v in value.items():
            key_text = str(k).lower()
            if any(key in key_text for key in keys):
                found.extend(_extract_numbers(v))
            found.extend(_collect_keyed_numbers(v, keys))
    elif isinstance(value, list):
        for item in value:
            found.extend(_collect_keyed_numbers(item, keys))
    return found


def _extract_numbers(value: Any) -> list[float]:
    if isinstance(value, (int, float)):
        return [float(value)]
    if isinstance(value, dict):
        numbers: list[float] = []
        if "value" in value:
            numbers.extend(_extract_numbers(value["value"]))
        elif "numeric_value" in value:
            numbers.extend(_extract_numbers(value["numeric_value"]))
        else:
            for item in value.values():
                numbers.extend(_extract_numbers(item))
        return numbers
    if isinstance(value, list):
        numbers: list[float] = []
        for item in value:
            numbers.extend(_extract_numbers(item))
        return numbers
    return []
